### PR TITLE
Add signature and html download path

### PR DESCRIPTION
**Pull request by alorenzo175**
Added the download path (/reports/<uuid>/html) but no link in report yet. Downloads a zip file with the GPG signature, report, and various checksums.

### CODE REVIEW

**Comment by alorenzo175** [comment]
closes https://github.com/SolarArbiter/solarforecastarbiter-core/issues/157 and makes progress on https://github.com/SolarArbiter/solarforecastarbiter-core/issues/158

**Comment by alorenzo175** [comment]
For now, the signing happens on the dashboard. I do think we might consider moving report view (html body, full html, pdf, etc) to the API and have a background job handle it and avoid blocking any flask threads.

**Comment by alorenzo175** [comment]
Ah I meant moving the final report templating and signing to the API since it may take some time to do things like create the final PDF of a report. Hashing/signing is quick.

**Comment by lboeman** [comment]
Ah okay :+1:

**Pull request merged**
